---
version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./message_broker_data/zookeeper/data:/var/lib/zookeeper/data
      - ./message_broker_data/zookeeper/log:/var/lib/zookeeper/log
      - ./message_broker_data/zookeeper/secrets:/etc/zookeeper/secrets
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./message_broker_data/kafka/secrets:/etc/kafka/secrets
      - ./message_broker_data/kafka/data:/var/lib/kafka/data
    networks:
      - kafka-network

networks:
  kafka-network:
    external: false